### PR TITLE
Test improvements

### LINKED ISSUE #29: Google/YouTube API quotaExceeded exception.
#### Description
If we exceed the request rate limit for youtube data api a [`quotaExceeded`](https://github.com/YouTubeNLP/Backend/runs/963159583?check_suite_focus=true) with error code `403` is generated which needs proper handling. This is happening only for our `tests/` as it creates multiple threads which increase the request to the youtube api linearly. 

#### Possible solutions
1. Change the way we're testing our API, ex. break the load testing and mock testing to separate tests.
2. Initiate the github action event when we make a [pull request](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags) to `master` rather than [push](https://github.com/YouTubeNLP/Backend/blob/master/.github/workflows/test.yml#L4).
3. Change quota in the Google API console.

#### Screenshots
image

#### Helpful resources
Quota usage: https://developers.google.com/youtube/v3/getting-started#quota
Errors: https://developers.google.com/youtube/v3/docs/errors
Quota extension: https://support.google.com/youtube/contact/yt_api_form

### PR DESCRIPTION
**Pull request by edwhuang23**
## Description

Unit tests have been changed so that tests do not rely solely on a static response. Instead the tests will check that the endpoint is working by checking for error code. Documentation has also been changed in accordance with fixes to directory structure.

Fixes #29

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?
Pytest has been run and there are 2 errors that remain. These errors are not due to errors with the test itself.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by pandevim — CHANGES_REQUESTED** [review]
It would be awesome if you updated the doc with this PR only and not to `dev` branch. But that is okay.
Nice this is complete, can you update the tests running on Github Action as well, in this same PR?

**Comment by edward2018211** [comment]
I just checked and I believe the tests are being run as part of GitHub Actions as well since ```pytest``` is begin executed.

**Comment by pandevim** [comment]
> error with wordCloud and rootResponse endpoints.

Can you elaborate on these errors and why they're happening?

**Comment by YashSahsani** [comment]
> > error with wordCloud and rootResponse endpoints.
> 
> Can you elaborate on these errors and why they're happening?
I think fixed them but still i will test and tell you guys.

**Comment by edward2018211** [comment]
wordCloud is due to runtime error in the code that causes the endpoint not to work properly I believe. rootResponse is due to a comparison issue between the rootResponse.txt and the response from the endpoint. They don't seems to be matching up somewhere although I have taken a look at it and can't figure out why they don't match up.

**Comment by pandevim** [comment]
I'm not sure why we have tests for root response, there is no need to have it!
Will remove that and as for `wordCloud` need to fix that.

**Comment by YashSahsani** [comment]
image

**Pull request merged**
